version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi3-homeassistant
    volumes:
      - /apps/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: host
