homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 75
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: GB
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: darksky
    api_key: !secret darksky_key
    units: auto
    monitored_conditions:
      - summary
      - icon
      - nearest_storm_distance
  - platform: template
    sensors:
      lounge:
        value_template: '{{ states.remote.lounge.attributes.current_activity }}'
        friendly_name: 'Lounge TV'

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

switch:
  - platform: tplink
    name: Lounge lamp
    host: 192.168.0.50
  - platform: tplink
    name: Cabinet lights
    host: 192.168.0.51
  - platform: lightwave
    devices:
      R1D2:
        name: Firepit lights
      R1D3:
        name: Kitchen
      R1D4:
        name: Spotlights
      R1D5:
        name: Water feature
      R1D6:
        name: Water feature light
      R1D7:
        name: Floodlight
      R2D1:
        name: Cave lights

light:
  - platform: template
    lights:
      lounge_lamp:
        friendly_name: 'Lounge lamp'
        level_template: '{{ 255 if is_state("switch.lounge_lamp", "on") else 0 }}'
        value_template: '{{ is_state("switch.lounge_lamp", "on") }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.lounge_lamp
        turn_off:
          service: switch.turn_off
          entity_id: switch.lounge_lamp
        set_level:
          service_template: switch.turn_'{{ "off" if brightness == 0 else "on" }}'
          entity_id: switch.lounge_lamp

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

