# Use this file to store secrets like usernames and passwords.
# Learn more at https://home-assistant.io/docs/configuration/secrets/
http_password: welcome
latitude_home: 0.0
longitude_home: 0.0
darksky_key: somekey
